Repository Chahalor/connect4, pull requests merged in 2025-05, with the labels that each got.

#3 fix:error-struct-parserv4
  src/Parseur/Parseur.c
  src/Parseur/Parseur.h
Labels: Forbidden Function

#9 fix: skill issue il the core init
  src/AI/AI.h
  src/Core/Core.c
  src/Interface/Interface.h
  src/main.c
Labels: bug

#10 Chore: Fix typo in parser (from parseur)
  .dev/Connect4.drawio
  Makefile
  src/Core/Core.h
  src/Core/_internal/_core.h
  src/Parser/Parser.c
  src/Parser/Parser.h
  src/Parser/makefile.mk
  src/Parseur/makefile.mk
  src/main.c
Labels: documentation

#11 Chore: Local .gitignore adaptation (add connect4 binary and .idea)
  .gitignore
Labels: documentation

#18 Advanced cli
  .dev/TODO.md
  Makefile
  connect4
  src/AI/AI.c
  src/AI/_internal/_evaluate.c
  src/Core/Core.h
  src/Core/_internal/_core.c
  src/Core/_internal/_core.h
  src/Interface/Interface.c
  src/Interface/_internal/_interface.h
  src/ft_printf/_internal/_ft_printf.h
  src/ft_printf/_internal/printf/writer.c
  src/ft_printf/_internal/utils/_utils.c
  src/ft_printf/ft_printf.c
  src/ft_printf/ft_printf.h
  src/ft_printf/interface.c
  src/ft_printf/makefile.mk
  src/main.c
Labels: bug, enhancement

#21 fix: interface: nice invalide user input handler
  .dev/TODO.md
  global/config.h
  src/Interface/Interface.c
  src/Parser/Parser.c
  src/Utils/Utils.c
  src/Utils/Utils.h
Labels: bug, enhancement

#25 add Ai to main
  src/AI/_internal/_evaluate.c
Labels: enhancement

#27 Chore: Removing .dev directory & auto.sh
  .dev/Connect4.drawio
  .dev/Interface
  .dev/TODO.md
  .dev/test.c
  auto.sh
Labels: documentation
